// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdivofS22en3EsV_2RyxHogazaBkA-2ko',
    appId: '1:897652991129:web:57d8d15d232854aac38408',
    messagingSenderId: '897652991129',
    projectId: 'dblugares',
    authDomain: 'dblugares.firebaseapp.com',
    storageBucket: 'dblugares.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_wECg2XwmkAHTvYuknECuAVgjR5Jt3w',
    appId: '1:897652991129:android:1e6f01448fe63e6fc38408',
    messagingSenderId: '897652991129',
    projectId: 'dblugares',
    storageBucket: 'dblugares.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzz4jvE_I4sxay9PHtSbMRKup9Q0QN74',
    appId: '1:897652991129:ios:ea3272323bfcfcadc38408',
    messagingSenderId: '897652991129',
    projectId: 'dblugares',
    storageBucket: 'dblugares.appspot.com',
    iosClientId: '897652991129-qajadhfaj9hedj8tgs001n7km4faqiqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.lugaresCercanos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzz4jvE_I4sxay9PHtSbMRKup9Q0QN74',
    appId: '1:897652991129:ios:391eb130c6aed7cac38408',
    messagingSenderId: '897652991129',
    projectId: 'dblugares',
    storageBucket: 'dblugares.appspot.com',
    iosClientId: '897652991129-bi3l9ejia2k2l30i9v0mibec9git1iej.apps.googleusercontent.com',
    iosBundleId: 'com.example.lugaresCercanos.RunnerTests',
  );
}
